version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - USER_SERVICE_URL=http://user-service:8081