openapi: 3.0.1
info:
  title: User Service API
  description: API для управления пользователями
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

paths:
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Получить пользователя по ID
      description: Возвращает информацию о конкретном пользователе
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID пользователя
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неверные параметры запроса
        '404':
          description: Пользователь не найден
    delete:
      tags:
        - Users
      summary: Удалить пользователя
      description: Удаляет пользователя по указанному ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID пользователя для удаления
      responses:
        '200':
          description: Пользователь успешно удален
        '400':
          description: Неверные параметры запроса

  /users:
    post:
      tags:
        - Users
      summary: Создать нового пользователя
      description: Создает нового пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Успешное создание пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неверные параметры запроса

    get:
      tags:
        - Users
      summary: Получить всех пользователей
      description: Возвращает список всех пользователей системы
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор пользователя
        name:
          type: string
          description: Имя пользователя
        email:
          type: string
          format: email
          description: Email пользователя
        creationDate:
          type: string
          format: date-time
          description: Дата создания пользователя
      required:
        - name
        - email

    UserDTO:
      type: object
      properties:
        name:
          type: string
          description: Имя пользователя
        email:
          type: string
          format: email
          description: Email пользователя
      required:
        - name
        - email

  responses:
    BadRequest:
      description: Неверные параметры запроса
    NotFound:
      description: Ресурс не найден