name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['order-service', 'user-service']
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        working-directory: ${{ matrix.service }}
        run: mvn clean package
        
      - name: Upload artifact 
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.service }}-artifact
          path: ${{ matrix.service }}/target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['order-service', 'user-service']
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: mvn test

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['order-service', 'user-service']
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: docker build -t ${{ matrix.service }} .

  docker-compose:
    needs: [build, docker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build with docker-compose
        run: docker-compose build
